# Generated by Django 5.0.4 on 2024-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
